config/routes.rb
BankingRails::Application.routes.draw do

  get "sessions/new"
  root 'welcome#outer'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :articles
  resources :comments
  resources :users

  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, presence: true, length: { maximum: 11 },
            uniqueness: { case_sensitive: false }
  validates :address, presence: true, length: { maximum: 30 }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end

  end

  def show
    @article = Article.find(params[:id])
    render 'data/course_1'
  end

  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

  def hello
    render text: "hello,world"
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(phone: params[:session][:phone])
    if !user
      user = User.find_by(name: params[:session][:phone])
    end

    if user && user.authenticate(params[:session][:password])
      debugger
      log_in user
      # redirect_to user
      redirect_to root_url
    else
      debugger
      flash[:danger] = 'Invalid phone/password combination'
      render 'new'
    end
  end


  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    # debugger
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to 正信医疗管理系统!"
      # redirect_to @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :phone, :address, :password,
                                   :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
      gravatar_id = Digest::MD5::hexdigest(user.name.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:</h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>课程列表</h1>

<table>
  <tr>
    <th>名字</th>
    <th>                      </th>
    <th>  内容     </th>
  </tr>

  <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td></td>
        <td><%= article.text %></td>
        <td><%= link_to '点击查看', article_path(article) %></td> <!--  -->
        <td><%= link_to '编辑', edit_article_path(article) %></td>
        <!--<td><%= link_to 'Destroy', article_path(article),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>


<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', articles_path %>
| <%= link_to 'Edit', edit_article_path(@article) %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure to delete this comment?' } %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BankingRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %> <div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li> <% end %>
  </ul>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>新用户注册</h1>
<p>新会员欢迎您!注册完成后请使用手机号或用户名登陆</p>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label "用户名" %>
        <%= f.text_field :name %>
        <p> </p>
        <%= f.label "手机号" %>
        <%= f.text_field :phone %>
        <p> </p>
        <%= f.label "医院名称" %>
        <%= f.text_field :address %>
        <p> </p>
        <%= f.label "密码" %>
        <%= f.password_field :password %>
        <p> </p>
        <%= f.label :password_confirmation, "确认密码" %>
        <%= f.password_field :password_confirmation %>
        <p> </p>
        <%= f.submit "创建账号", class: "btn btn-primary" %> <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>个人信息</h1>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <ul class="nav navbar-nav pull-right">
        <li><%= gravatar_for @user %></li>
        <li>用户名: <%= @user.name %></li>
        <li>手机号: <%= @user.phone %></li>
        <li>所属医院: <%= @user.address %></li>
      </ul>
    </section>
  </aside>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>北京正信医疗培训</title>
      <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
      <![endif]-->
    </head>
    <body>
    <h1>北京正信医疗培训系统欢迎您!</h1>
        <header class="navbar navbar-fixed-top navbar-inverse">
          <div class="container">
            <!--<%= link_to "sample app", '#', id: "logo" %>-->
            <nav>
              <ul class="nav navbar-nav pull-right">
                <!--<li><%= link_to "Home",   '#' %></li>-->
                <li><%= link_to "注册", signup_path %></li>
                <% if logged_in? %>
                    <li><%= link_to "个人页", current_user %></li>
                    <!--<li><%= link_to "Settings", '#' %></li>-->
                    <li><%= link_to '查看我的课程', controller: 'articles' %></li>
                    <li>
                      <%= link_to "退出登陆", logout_path, method: "delete" %>
                    </li>
                <% else %>
                    <li><%= link_to "登陆", login_path %></li>
                <% end %>
              </ul> </nav>
          </div>
        </header>


        <!--<h2>请登录</h2>-->

        <!--<%= link_to '添加课程', new_article_path %>-->

        <div class="container">
          <%= yield %>
        </div>
    </body>
</html>